[package]
name = "rustex_java"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib","lib"]
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustex = { path = "../rustex" }
robusta_jni = "0.2.0"
