name := "RusTeX"
version := "0.2"
scalaVersion := "2.13.4"
Compile/scalaSource := baseDirectory.value / "src" / "main" / "scala"
libraryDependencies += "org.apache.commons" % "commons-compress" % "1.2"