[package]
name = "rustex"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]
path = "src/lib.rs"

[[bin]]
name = "rustex"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

#[build-dependencies]
#bindgen = "0.59"
#pkg-config = "0.3"

[dependencies]
lazy_static = "1.4.0"
itertools = "0.10.5"
pathdiff = "0.2.1"
colored="2.0.0"
ansi_term = "0.12.1"
backtrace = "0.3.66"
chrono = "0.4.22"
regex = "1.6.0"
md5 = "0.7.0"
image = "0.24.4"
base64 =  "0.13.0"
clap = { version = "3.2.22", features = ["derive"] }
pdfium-render = "0.6" #, features = ["static"] }
#magick_rust = { path = "../magick-rust" }

#fixed = "1.11.0"
#libc = "0.2.0"
#kpathsea = "0.2.3"
#kpathsea = { path = "../kpathsea" }