[package]
name = "rustex"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib","lib"]
path = "src/lib.rs"

[[bin]]
name = "rustex"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
itertools = "0.10.1"
pathdiff = "0.1.0"
colored="2"
ansi_term = "0.12.1"
backtrace = "0.3"
chrono = "0.4"
#libc = "0.2.0"
# kpathsea = "0.2.2"