name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Install kpathsea
      run: sudo apt install libkpathsea-dev
    - name: Build
      run: cd rustex && cargo build --verbose
  deployment:
    runs-on: ubuntu-18.04
    environment: production
    steps:
    - name: Install kpathsea
      run: sudo apt install libkpathsea-dev
    -name: Deploy
      run: cd rustex && cargo build --release --target x86_64-unknown-linux-gnu