name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install kpathsea
      run: sudo apt install libkpathsea-dev
    - name: Build
      run: cd rustex && cargo build --verbose
