name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Install kpathsea
      run: sudo apt install libkpathsea-dev
    - name: Build
      run: cd rustex && cargo build --release --target x86_64-unknown-linux-gnu
    - name: Install texlive
      run: sudo apt install texlive
    - name: Test latex.ltx
      run: cd rustex/target/x86_64-unknown-linux-gnu/release && ./rustex
  deploy_linux:
    runs-on: ubuntu-18.04
    environment: production
    steps:
    - uses: actions/checkout@v2
    - name: Deploy Linux
      run: cd rustex && cargo build --release --target x86_64-unknown-linux-gnu
    - name: Upload Linux
      uses: actions/upload-artifact@v2
      with:
        name: linux
        path: |
          ./rustex/target/x86_64-unknown-linux-gnu/release/librustex.rlib
          ./rustex/target/x86_64-unknown-linux-gnu/release/librustex.so
          ./rustex/target/x86_64-unknown-linux-gnu/release/rustex
  deploy_windows:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v2
    - name: Install Tools
      run: sudo apt install mingw-w64 # libkpathsea-dev
    - name: rustups
      run: rustup target add i686-pc-windows-gnu # && rustup target add x86_64-apple-darwin
    - name: linker fixes
      run: cd ~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/i686-pc-windows-gnu/lib/self-contained && mv crt2.o crt2.o.ori && mv dllcrt2.o dllcrt2.o.ori && cp /usr/i686-w64-mingw32/lib/crt2.o . && cp /usr/i686-w64-mingw32/lib/dllcrt2.o .
    - name: Deploy Windows
      run: cd rustex && cargo build --release --target i686-pc-windows-gnu
    - name: Upload Windows
      uses: actions/upload-artifact@v2
      with:
        name: windows
        path: |
          ./rustex/target/i686-pc-windows-gnu/release/librustex.rlib
          ./rustex/target/i686-pc-windows-gnu/release/rustex.dll
          ./rustex/target/i686-pc-windows-gnu/release/rustex.dll.lib
          ./rustex/target/i686-pc-windows-gnu/release/rustex.exe
